--
-- PostgreSQL database dump
--

-- Dumped from database version 13.18 (Debian 13.18-1.pgdg120+1)
-- Dumped by pg_dump version 13.18 (Debian 13.18-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.carrito (
    id bigint NOT NULL,
    precio_total double precision NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.carrito OWNER TO iweb;

--
-- Name: carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.categorias (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.categorias OWNER TO iweb;

--
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentarios; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.comentarios (
    id bigint NOT NULL,
    contenido character varying(500) NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    visible boolean NOT NULL,
    id_producto bigint NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.comentarios OWNER TO iweb;

--
-- Name: comentarios_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.comentarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.pagos (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    ticket_ext character varying(255) NOT NULL,
    total double precision NOT NULL,
    pedido_id bigint
);


ALTER TABLE public.pagos OWNER TO iweb;

--
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametros_comercio; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.parametros_comercio (
    id bigint NOT NULL,
    clave character varying(255) NOT NULL,
    valor character varying(255) NOT NULL
);


ALTER TABLE public.parametros_comercio OWNER TO iweb;

--
-- Name: parametros_comercio_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.parametros_comercio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametros_comercio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.pedido (
    id bigint NOT NULL,
    detalles character varying(255),
    estado character varying(255) NOT NULL,
    fecha_pedido timestamp(6) without time zone NOT NULL,
    numero_pedido character varying(255) NOT NULL,
    tipo_entrega character varying(255),
    total double precision NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.pedido OWNER TO iweb;

--
-- Name: pedido_completados; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.pedido_completados (
    id bigint NOT NULL,
    comercio_nombre character varying(255),
    estado_pago character varying(255),
    fecha timestamp(6) without time zone,
    importe double precision NOT NULL,
    pago_id bigint,
    pedido_id bigint,
    tarjeta character varying(255),
    tarjeta_pago_numero character varying(255),
    ticket_ext character varying(255)
);


ALTER TABLE public.pedido_completados OWNER TO iweb;

--
-- Name: pedido_completados_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.pedido_completados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_completados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.producto_carrito (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario double precision NOT NULL,
    subtotal double precision NOT NULL,
    id_carrito bigint NOT NULL,
    id_producto bigint NOT NULL
);


ALTER TABLE public.producto_carrito OWNER TO iweb;

--
-- Name: producto_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.producto_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_pedido; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.producto_pedido (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario double precision NOT NULL,
    subtotal double precision NOT NULL,
    id_pedido bigint NOT NULL,
    id_producto bigint NOT NULL
);


ALTER TABLE public.producto_pedido OWNER TO iweb;

--
-- Name: producto_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.producto_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    categoria character varying(255) NOT NULL,
    descripcion character varying(500) NOT NULL,
    foto character varying(255),
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL,
    stock integer NOT NULL
);


ALTER TABLE public.productos OWNER TO iweb;

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    administrador boolean NOT NULL,
    bloqueado boolean NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date,
    nombre character varying(255),
    password character varying(255)
);


ALTER TABLE public.usuarios OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

CREATE SEQUENCE public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuarios_id_seq OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: iweb
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Data for Name: carrito; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.carrito (id, precio_total, id_usuario) FROM stdin;
2	0	9
3	56	2
4	35	13
5	37	6
6	101	7
7	45	8
8	45	5
1	0	4
\.


--
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.categorias (id, nombre) FROM stdin;
1	Chaquetas
2	Pantalones
3	Zapatos
\.


--
-- Data for Name: comentarios; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.comentarios (id, contenido, fecha_creacion, visible, id_producto, id_usuario) FROM stdin;
1	Me ha encantado	2025-01-16 07:03:33.866	f	2	4
2	muy buena calidad	2025-01-16 07:13:25.178	t	3	4
3	mi hijo no se las quita para nada	2025-01-16 07:13:58.923	t	3	4
\.


--
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.pagos (id, estado, fecha, ticket_ext, total, pedido_id) FROM stdin;
1	ACEPT1000	2025-01-16 23:20:00	PED-229A1203	249	\N
2	ACEPT1000	2025-01-16 23:21:00	PED-A64F63D4	37	\N
3	ACEPT1000	2025-01-16 23:29:00	PED-33DE83CA	170	9
\.


--
-- Data for Name: parametros_comercio; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.parametros_comercio (id, clave, valor) FROM stdin;
1	apiKey	mi-api-key-12346
2	nombre	JaySports
\.


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.pedido (id, detalles, estado, fecha_pedido, numero_pedido, tipo_entrega, total, id_usuario) FROM stdin;
2	\N	PENDIENTE	2025-01-16 17:12:47.285457	PED-B2AC69D0	\N	35	13
3	\N	PENDIENTE	2025-01-16 17:12:47.302355	PED-4D962E4A	\N	35	13
4	\N	PENDIENTE	2025-01-16 17:13:26.651525	PED-76696C4A	\N	37	6
5	\N	PENDIENTE	2025-01-16 18:12:29.70226	PED-92F3186F	\N	0	7
6	\N	PENDIENTE	2025-01-16 18:13:36.856725	PED-166BF731	\N	45	8
7	\N	PENDIENTE	2025-01-16 18:20:15.615223	PED-367339BD	\N	45	5
1	\N	COMPLETADO	2025-01-16 20:23:24.585093	PED-229A1203	\N	249	4
8	\N	COMPLETADO	2025-01-16 23:21:36.093607	PED-A64F63D4	\N	37	4
9	\N	COMPLETADO	2025-01-16 23:22:01.904222	PED-33DE83CA	\N	170	4
10	\N	PENDIENTE	2025-01-16 23:31:55.737174	PED-74861A77	\N	0	4
\.


--
-- Data for Name: pedido_completados; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.pedido_completados (id, comercio_nombre, estado_pago, fecha, importe, pago_id, pedido_id, tarjeta, tarjeta_pago_numero, ticket_ext) FROM stdin;
1	Tienda de Juegos de Mesa Chessyx	ACEPT1000	2025-01-16 17:46:00	888.888	43	4	3176317631763176	3176317631763176	TICKET-888
2	Tienda de Juegos de Mesa Chessyx	ACEPT1000	2025-01-16 17:48:00	888.888	44	4	3148314831483148	3148314831483148	TICKET-888
3	Tienda de Juegos de Mesa Chessyx	ACEPT1000	2025-01-16 17:49:00	888.888	45	4	1111111111111111	1111111111111111	TICKET-888
4	Tienda de Juegos de Mesa Chessyx	ACEPT1000	2025-01-16 18:20:00	45	46	4	6969696969696969	6969696969696969	PED-367339BD
5	Tienda de Juegos de Mesa Chessyx	ACEPT0001	2025-01-16 19:45:00	204	47	4	2000123412341234	2000123412341234	PED-481C3D67
6	Tienda de Juegos de Mesa Chessyx	ACEPT1000	2025-01-16 20:21:00	204	48	4	1111111111111111	1111111111111111	PED-29A81CE6
\.


--
-- Data for Name: producto_carrito; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.producto_carrito (id, cantidad, precio_unitario, subtotal, id_carrito, id_producto) FROM stdin;
4	1	45	45	2	6
5	1	56	56	3	5
10	1	56	56	3	3
12	1	35	35	4	2
13	1	56	56	4	5
14	1	37	37	5	4
15	1	45	45	5	6
18	1	56	56	6	3
19	1	45	45	6	6
20	1	56	56	6	5
21	1	45	45	7	6
22	1	56	56	7	5
23	1	45	45	8	6
24	1	56	56	8	5
\.


--
-- Data for Name: producto_pedido; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.producto_pedido (id, cantidad, precio_unitario, subtotal, id_pedido, id_producto) FROM stdin;
1	2	45	90	1	6
2	2	56	112	1	5
3	4	35	140	1	2
4	2	23	46	1	7
5	3	37	111	1	4
6	1	47	47	1	10
7	4	56	224	1	3
8	1	35	35	2	2
9	1	56	56	2	5
10	1	35	35	3	2
11	1	56	56	3	5
12	1	37	37	4	4
13	1	45	45	4	6
14	1	56	56	5	3
15	1	45	45	6	6
16	1	56	56	6	5
17	1	45	45	7	6
18	1	56	56	7	5
19	2	56	112	1	3
20	1	56	56	1	5
21	2	45	90	1	6
22	2	56	112	1	3
23	1	56	56	1	5
24	2	45	90	1	6
25	2	56	112	1	3
26	1	56	56	1	5
27	2	45	90	1	6
28	1	23	23	1	7
29	2	56	112	1	3
30	1	56	56	1	5
31	2	45	90	1	6
32	1	23	23	1	7
33	2	56	112	1	3
34	1	56	56	1	5
35	2	45	90	1	6
36	1	23	23	1	7
37	2	56	112	1	3
38	1	56	56	1	5
39	2	45	90	1	6
40	1	23	23	1	7
41	2	56	112	1	3
42	1	56	56	1	5
43	2	45	90	1	6
44	1	23	23	1	7
45	2	56	112	1	3
46	1	56	56	1	5
47	2	45	90	1	6
48	1	23	23	1	7
49	2	56	112	1	3
50	1	56	56	1	5
51	2	45	90	1	6
52	1	23	23	1	7
53	1	35	35	1	2
54	2	56	112	1	3
55	1	56	56	1	5
56	2	45	90	1	6
57	1	23	23	1	7
58	1	35	35	1	2
59	2	56	112	1	3
60	1	56	56	1	5
61	2	45	90	1	6
62	1	23	23	1	7
63	1	35	35	1	2
64	2	56	112	1	3
65	1	56	56	1	5
66	2	45	90	1	6
67	1	23	23	1	7
68	1	35	35	1	2
69	2	56	112	1	3
70	1	56	56	1	5
71	2	45	90	1	6
72	1	23	23	1	7
73	1	35	35	1	2
74	2	56	112	1	3
75	1	56	56	1	5
76	2	45	90	1	6
77	1	23	23	1	7
78	1	35	35	1	2
79	2	56	112	1	3
80	1	56	56	1	5
81	2	45	90	1	6
82	1	23	23	1	7
83	1	35	35	1	2
84	1	37	37	1	4
85	2	56	112	1	3
86	1	56	56	1	5
87	2	45	90	1	6
88	1	23	23	1	7
89	1	35	35	1	2
90	1	37	37	1	4
91	2	56	112	1	3
92	1	56	56	1	5
93	2	45	90	1	6
94	1	23	23	1	7
95	1	35	35	1	2
96	1	37	37	1	4
97	2	56	112	1	3
98	1	56	56	1	5
99	2	45	90	1	6
100	1	23	23	1	7
101	1	35	35	1	2
102	1	37	37	1	4
103	1	56	56	1	9
104	2	56	112	1	3
105	1	56	56	1	5
106	2	45	90	1	6
107	1	23	23	1	7
108	1	35	35	1	2
109	1	37	37	1	4
110	1	56	56	1	9
111	2	56	112	1	3
112	1	56	56	1	5
113	2	45	90	1	6
114	1	23	23	1	7
115	1	35	35	1	2
116	1	37	37	1	4
117	1	56	56	1	9
118	2	56	112	1	3
119	1	56	56	1	5
120	2	45	90	1	6
121	1	23	23	1	7
122	1	37	37	1	4
123	1	56	56	1	9
124	2	35	70	1	2
125	2	56	112	1	3
126	2	45	90	1	6
127	1	23	23	1	7
128	1	37	37	1	4
129	1	56	56	1	9
130	2	35	70	1	2
131	2	56	112	1	5
132	2	56	112	1	3
133	2	45	90	1	6
134	1	23	23	1	7
135	1	37	37	1	4
136	1	56	56	1	9
137	2	35	70	1	2
138	2	56	112	1	5
139	1	67	67	1	11
140	2	56	112	1	3
141	2	45	90	1	6
142	1	23	23	1	7
143	1	37	37	1	4
144	1	56	56	1	9
145	2	35	70	1	2
146	2	56	112	1	5
147	1	67	67	1	11
148	2	56	112	1	3
149	2	45	90	1	6
150	1	23	23	1	7
151	1	37	37	1	4
152	1	56	56	1	9
153	2	35	70	1	2
154	2	56	112	1	5
155	1	67	67	1	11
156	1	35	35	1	13
157	2	56	112	1	3
158	2	45	90	1	6
159	1	23	23	1	7
160	1	37	37	1	4
161	1	56	56	1	9
162	2	35	70	1	2
163	2	56	112	1	5
164	1	67	67	1	11
165	1	35	35	1	13
166	2	45	90	1	6
167	1	23	23	1	7
168	1	37	37	1	4
169	1	56	56	1	9
170	2	35	70	1	2
171	2	56	112	1	5
172	1	67	67	1	11
173	1	35	35	1	13
174	1	23	23	1	7
175	1	37	37	1	4
176	1	56	56	1	9
177	2	35	70	1	2
178	2	56	112	1	5
179	1	67	67	1	11
180	1	35	35	1	13
181	1	37	37	1	4
182	1	56	56	1	9
183	2	35	70	1	2
184	2	56	112	1	5
185	1	67	67	1	11
186	1	35	35	1	13
187	1	56	56	1	9
188	2	35	70	1	2
189	2	56	112	1	5
190	1	67	67	1	11
191	1	35	35	1	13
192	2	35	70	1	2
193	2	56	112	1	5
194	1	67	67	1	11
195	1	35	35	1	13
196	2	56	112	1	5
197	1	67	67	1	11
198	1	35	35	1	13
199	1	67	67	1	11
200	1	35	35	1	13
201	1	67	67	1	11
202	1	35	35	1	13
203	1	67	67	1	11
204	1	35	35	1	13
205	1	67	67	1	11
206	1	35	35	1	13
207	1	67	67	1	11
208	1	35	35	1	13
209	1	67	67	1	11
210	1	35	35	1	13
211	1	35	35	1	2
212	1	67	67	1	11
213	1	35	35	1	13
214	1	35	35	1	2
215	1	67	67	1	11
216	1	35	35	1	13
217	1	35	35	1	2
218	1	37	37	1	4
219	1	67	67	1	11
220	1	35	35	1	13
221	1	35	35	1	2
222	1	37	37	1	4
223	1	67	67	1	11
224	1	35	35	1	13
225	1	35	35	1	2
226	1	37	37	1	4
227	1	67	67	1	11
228	1	35	35	1	13
229	1	35	35	1	2
230	1	37	37	1	4
231	1	67	67	1	11
232	1	35	35	1	13
233	1	35	35	1	2
234	1	37	37	1	4
235	1	67	67	1	11
236	1	35	35	1	13
237	1	35	35	1	2
238	1	37	37	1	4
239	1	67	67	1	11
240	1	35	35	1	13
241	1	35	35	1	2
242	1	37	37	1	4
243	1	45	45	1	6
244	1	67	67	1	11
245	1	35	35	1	13
246	1	35	35	1	2
247	1	37	37	1	4
248	1	45	45	1	6
249	1	67	67	1	11
250	1	35	35	1	13
251	1	35	35	1	2
252	1	37	37	1	4
253	1	45	45	1	6
254	1	35	35	1	13
255	1	35	35	1	2
256	1	37	37	1	4
257	1	45	45	1	6
258	1	35	35	1	2
259	1	37	37	1	4
260	1	45	45	1	6
261	1	37	37	1	4
262	1	45	45	1	6
263	1	37	37	1	4
264	1	37	37	1	4
265	1	23	23	1	7
266	1	37	37	1	4
267	1	23	23	1	7
268	1	37	37	1	4
269	1	35	35	1	2
270	1	23	23	1	7
271	1	37	37	1	4
272	1	35	35	1	2
273	1	23	23	1	7
274	3	37	111	1	4
275	2	35	70	1	2
276	1	23	23	1	7
277	3	37	111	1	4
278	2	35	70	1	2
279	1	23	23	1	7
280	3	37	111	1	4
281	2	35	70	1	2
282	1	23	23	1	7
283	3	37	111	1	4
284	2	35	70	1	2
285	1	23	23	1	7
286	3	37	111	1	4
287	2	35	70	1	2
288	1	23	23	1	7
289	3	37	111	1	4
290	2	35	70	1	2
291	1	23	23	1	7
292	3	37	111	1	4
293	2	35	70	1	2
294	1	23	23	1	7
295	3	37	111	1	4
296	2	35	70	1	2
297	1	23	23	1	7
298	3	37	111	1	4
299	2	35	70	1	2
300	1	23	23	1	7
301	3	37	111	1	4
302	2	35	70	1	2
303	1	23	23	1	7
304	3	37	111	1	4
305	2	35	70	1	2
306	1	23	23	1	7
307	3	37	111	1	4
308	2	35	70	1	2
309	1	23	23	1	7
310	3	37	111	1	4
311	2	35	70	1	2
312	1	23	23	1	7
313	3	37	111	1	4
314	2	35	70	1	2
315	1	45	45	1	6
316	1	37	37	8	4
317	1	56	56	9	3
318	1	23	23	9	7
319	1	56	56	9	9
320	1	35	35	9	13
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.productos (id, categoria, descripcion, foto, nombre, precio, stock) FROM stdin;
2	hola	ddddddddddddddddddddd	bolso_puma_coperni.jpg	bolso puma coperni 	35	5
3	botas	ddddddddddddddddddddd	botas_futbol_ultra_5.jpg	botas futbol ultra 5	56	6
4	botas 	eeeeeeeeeeeeeeeee	botas_puma_evolve_niño.jpg	botas puma evolve niño	37	5
5	camiseta	eeeeeeeeeeeeeeeeeeeeeee	camiseta_ac_milan.jpg	camiseta ac milan	56	3
6	camiseta	ssssssssssssssssssssssssss	camiseta_manchester_city.jpg	camiseta machester city	45	3
7	camiseta	aaaaaaaaaaaaaaaaaa	camiseta_puma_rocket_league.jpg	camiseta puma rocket league	23	3
8	camiseta	erwgeeeeeeee	camiseta_pumaSquad_negra.jpg	camiseta puma squad negra	47	4
9	camiseta	ddddddddddddddddddddddddd	camiseta_skepta_blanca.jpg	camiseta skepta blanca	56	4
10	chaqueta	wdwwwwwwwwwwww	chaqueta_minicats_niños.jpg	chaqueta minicats niños	47	45
11	chaqueta	wfeeeeeeeeeeeeeeee	chaqueta_reversible_negra.jpg	chaqueta reversible negra	67	5
12	chaqueta	wwwwwwwwwwwwwwwwww	chaqueta_skepta_negra.jpg	chaqueta skepta negra	35	2
13	chaqueta	eeeeeeeeeeeeeeeeeeeeeeeeeeeee	chaqueta_verde_puma.jpg	chaqueta verde puma	35	5
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.usuarios (id, administrador, bloqueado, email, fecha_nacimiento, nombre, password) FROM stdin;
2	t	f	admin@gmail.com	1999-01-01	admin	admin
4	f	f	user@gmail.com	1997-01-01	user	user
6	f	f	user3@gmail.com	1999-01-01	user3	user3
7	f	f	user4@gmail.com	1900-01-01	user4	user4
8	f	f	user5@gmail.com	1990-01-01	user5	user5
9	f	f	user6@gmail.com	2004-02-01	user6	user6
5	f	f	user2@gmail.com	1999-01-01	user2	user2
13	f	f	chope@gmail.com	2020-10-02	chope	chope
\.


--
-- Name: carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.carrito_id_seq', 8, true);


--
-- Name: categorias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.categorias_id_seq', 3, true);


--
-- Name: comentarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.comentarios_id_seq', 3, true);


--
-- Name: pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.pagos_id_seq', 3, true);


--
-- Name: parametros_comercio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.parametros_comercio_id_seq', 2, true);


--
-- Name: pedido_completados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.pedido_completados_id_seq', 6, true);


--
-- Name: pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.pedido_id_seq', 10, true);


--
-- Name: producto_carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.producto_carrito_id_seq', 42, true);


--
-- Name: producto_pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.producto_pedido_id_seq', 320, true);


--
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.productos_id_seq', 13, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 13, true);


--
-- Name: carrito carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT carrito_pkey PRIMARY KEY (id);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- Name: comentarios comentarios_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT comentarios_pkey PRIMARY KEY (id);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- Name: parametros_comercio parametros_comercio_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.parametros_comercio
    ADD CONSTRAINT parametros_comercio_pkey PRIMARY KEY (id);


--
-- Name: pedido_completados pedido_completados_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pedido_completados
    ADD CONSTRAINT pedido_completados_pkey PRIMARY KEY (id);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id);


--
-- Name: producto_carrito producto_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT producto_carrito_pkey PRIMARY KEY (id);


--
-- Name: producto_pedido producto_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_pedido
    ADD CONSTRAINT producto_pedido_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: carrito uk1wsroe3wjs4dtnskxrlh7sm71; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT uk1wsroe3wjs4dtnskxrlh7sm71 UNIQUE (id_usuario);


--
-- Name: pagos uk9ibmqk82q3wpbw2l1jcych5kv; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT uk9ibmqk82q3wpbw2l1jcych5kv UNIQUE (pedido_id);


--
-- Name: parametros_comercio ukapc14p5feudq4s2wmdov3ukta; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.parametros_comercio
    ADD CONSTRAINT ukapc14p5feudq4s2wmdov3ukta UNIQUE (clave);


--
-- Name: pedido ukj0l80ge0fmklge54qlnx8ovur; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT ukj0l80ge0fmklge54qlnx8ovur UNIQUE (numero_pedido);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: pedido fk1jrv9w6qwijj7gv47oulj0q92; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fk1jrv9w6qwijj7gv47oulj0q92 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: comentarios fk1p19mnmrhsp25p79cg1o7oke5; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fk1p19mnmrhsp25p79cg1o7oke5 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: producto_pedido fk61xpthuedk4fuxhy9ffbscog4; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_pedido
    ADD CONSTRAINT fk61xpthuedk4fuxhy9ffbscog4 FOREIGN KEY (id_pedido) REFERENCES public.pedido(id);


--
-- Name: producto_carrito fkht34thlww4903in1c6r1wmctl; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkht34thlww4903in1c6r1wmctl FOREIGN KEY (id_carrito) REFERENCES public.carrito(id);


--
-- Name: producto_pedido fkibkl5ly2c2gv0pcjp7nkp299l; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_pedido
    ADD CONSTRAINT fkibkl5ly2c2gv0pcjp7nkp299l FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- Name: carrito fkkg5h8ejijsgwfr68aoggh4l8m; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT fkkg5h8ejijsgwfr68aoggh4l8m FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: pagos fkrfwu5myi9ckac1yowi09m7gqv; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fkrfwu5myi9ckac1yowi09m7gqv FOREIGN KEY (pedido_id) REFERENCES public.pedido(id);


--
-- Name: producto_carrito fkstfkowpwxp1ih2nj3f8gwetqd; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkstfkowpwxp1ih2nj3f8gwetqd FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- Name: comentarios fktav859qubu54wj0m3blrh09l5; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fktav859qubu54wj0m3blrh09l5 FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- PostgreSQL database dump complete
--

